electricity <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
elec <- subset(electricity, Date == "1/2/2007" | Date == "2/2/2007")
elec$Global_active_power <- as.numeric(as.character(elec$Global_active_power))
png(file = "plot1.png", width = 480, height = 480)
hist(elec$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power(kilowatts)")
dev.off()
