electricity <- read.table("household_power_consumption.txt", sep = ";", header = TRUE)
elec <- subset(electricity, Date == "1/2/2007" | Date == "2/2/2007")
elec$Global_active_power <- as.numeric(as.character(elec$Global_active_power))
elec$Global_reactive_power <- as.numeric(as.character(elec$Global_reactive_power))
elec$Voltage <- as.numeric(as.character(elec$Voltage))
elec$Sub_metering_1 <- as.numeric(as.character(elec$Sub_metering_1))
elec$Sub_metering_2 <- as.numeric(as.character(elec$Sub_metering_2))
elec$Sub_metering_3 <- as.numeric(as.character(elec$Sub_metering_3))
time <- paste(as.character(elec$Date), as.character(elec$Time))
time <- strptime(time, format = "%d/%m/%Y %H:%M:%S")
png(file = "plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
plot(time, elec$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(time, elec$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(time, elec$Sub_metering_1, type = "l",
     ylab = "Energy sub metering", xlab="")
lines(time, elec$Sub_metering_2, col = "red")
lines(time, elec$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       lwd = 1, col = c("black", "red", "blue"), bty = "n")
plot(time, elec$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()